//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicResponse", Namespace="http://schemas.datacontract.org/2004/07/BDConection.Dto.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference.GetUsersResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference.GetPaySheetsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference.isValidResponse))]
    public partial class BasicResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSavedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSaved {
            get {
                return this.isSavedField;
            }
            set {
                if ((this.isSavedField.Equals(value) != true)) {
                    this.isSavedField = value;
                    this.RaisePropertyChanged("isSaved");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersResponse", Namespace="http://schemas.datacontract.org/2004/07/BDConection.Dto.Response")]
    [System.SerializableAttribute()]
    public partial class GetUsersResponse : WebApplication1.ServiceReference.BasicResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference.User[] UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPaySheetsResponse", Namespace="http://schemas.datacontract.org/2004/07/BDConection.Dto.Response")]
    [System.SerializableAttribute()]
    public partial class GetPaySheetsResponse : WebApplication1.ServiceReference.BasicResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference.PaySheet[] paySheetsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference.PaySheet[] paySheets {
            get {
                return this.paySheetsField;
            }
            set {
                if ((object.ReferenceEquals(this.paySheetsField, value) != true)) {
                    this.paySheetsField = value;
                    this.RaisePropertyChanged("paySheets");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="isValidResponse", Namespace="http://schemas.datacontract.org/2004/07/BDConection.Dto.Response")]
    [System.SerializableAttribute()]
    public partial class isValidResponse : WebApplication1.ServiceReference.BasicResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference.User UserInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference.User UserInfo {
            get {
                return this.UserInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInfoField, value) != true)) {
                    this.UserInfoField = value;
                    this.RaisePropertyChanged("UserInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BDConection.Dto.Common")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BreakFastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SavingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UseridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BreakFast {
            get {
                return this.BreakFastField;
            }
            set {
                if ((this.BreakFastField.Equals(value) != true)) {
                    this.BreakFastField = value;
                    this.RaisePropertyChanged("BreakFast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName {
            get {
                return this.FirstLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstLastNameField, value) != true)) {
                    this.FirstLastNameField = value;
                    this.RaisePropertyChanged("FirstLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Roleid {
            get {
                return this.RoleidField;
            }
            set {
                if ((this.RoleidField.Equals(value) != true)) {
                    this.RoleidField = value;
                    this.RaisePropertyChanged("Roleid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Savings {
            get {
                return this.SavingsField;
            }
            set {
                if ((this.SavingsField.Equals(value) != true)) {
                    this.SavingsField = value;
                    this.RaisePropertyChanged("Savings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName {
            get {
                return this.SecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondLastNameField, value) != true)) {
                    this.SecondLastNameField = value;
                    this.RaisePropertyChanged("SecondLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLogin {
            get {
                return this.UserLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginField, value) != true)) {
                    this.UserLoginField = value;
                    this.RaisePropertyChanged("UserLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Userid {
            get {
                return this.UseridField;
            }
            set {
                if ((this.UseridField.Equals(value) != true)) {
                    this.UseridField = value;
                    this.RaisePropertyChanged("Userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaySheet", Namespace="http://schemas.datacontract.org/2004/07/BDConection.Dto.Common")]
    [System.SerializableAttribute()]
    public partial class PaySheet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BreakFastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaysheetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SavingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UseridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BreakFast {
            get {
                return this.BreakFastField;
            }
            set {
                if ((this.BreakFastField.Equals(value) != true)) {
                    this.BreakFastField = value;
                    this.RaisePropertyChanged("BreakFast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName {
            get {
                return this.FirstLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstLastNameField, value) != true)) {
                    this.FirstLastNameField = value;
                    this.RaisePropertyChanged("FirstLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Paysheetid {
            get {
                return this.PaysheetidField;
            }
            set {
                if ((this.PaysheetidField.Equals(value) != true)) {
                    this.PaysheetidField = value;
                    this.RaisePropertyChanged("Paysheetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Savings {
            get {
                return this.SavingsField;
            }
            set {
                if ((this.SavingsField.Equals(value) != true)) {
                    this.SavingsField = value;
                    this.RaisePropertyChanged("Savings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName {
            get {
                return this.SecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondLastNameField, value) != true)) {
                    this.SecondLastNameField = value;
                    this.RaisePropertyChanged("SecondLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Userid {
            get {
                return this.UseridField;
            }
            set {
                if ((this.UseridField.Equals(value) != true)) {
                    this.UseridField = value;
                    this.RaisePropertyChanged("Userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isValid", ReplyAction="http://tempuri.org/IService1/isValidResponse")]
        WebApplication1.ServiceReference.isValidResponse isValid(string UserLogin, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isValid", ReplyAction="http://tempuri.org/IService1/isValidResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference.isValidResponse> isValidAsync(string UserLogin, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        WebApplication1.ServiceReference.GetUsersResponse GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference.GetUsersResponse> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveUser", ReplyAction="http://tempuri.org/IService1/SaveUserResponse")]
        WebApplication1.ServiceReference.BasicResponse SaveUser(WebApplication1.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveUser", ReplyAction="http://tempuri.org/IService1/SaveUserResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference.BasicResponse> SaveUserAsync(WebApplication1.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GeneratePaysheets", ReplyAction="http://tempuri.org/IService1/GeneratePaysheetsResponse")]
        WebApplication1.ServiceReference.BasicResponse GeneratePaysheets(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GeneratePaysheets", ReplyAction="http://tempuri.org/IService1/GeneratePaysheetsResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference.BasicResponse> GeneratePaysheetsAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaySheets", ReplyAction="http://tempuri.org/IService1/GetPaySheetsResponse")]
        WebApplication1.ServiceReference.GetPaySheetsResponse GetPaySheets(System.Nullable<int> Userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaySheets", ReplyAction="http://tempuri.org/IService1/GetPaySheetsResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference.GetPaySheetsResponse> GetPaySheetsAsync(System.Nullable<int> Userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaySheetById", ReplyAction="http://tempuri.org/IService1/GetPaySheetByIdResponse")]
        WebApplication1.ServiceReference.GetPaySheetsResponse GetPaySheetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPaySheetById", ReplyAction="http://tempuri.org/IService1/GetPaySheetByIdResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference.GetPaySheetsResponse> GetPaySheetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference.IService1>, WebApplication1.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ServiceReference.isValidResponse isValid(string UserLogin, string Password) {
            return base.Channel.isValid(UserLogin, Password);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference.isValidResponse> isValidAsync(string UserLogin, string Password) {
            return base.Channel.isValidAsync(UserLogin, Password);
        }
        
        public WebApplication1.ServiceReference.GetUsersResponse GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference.GetUsersResponse> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public WebApplication1.ServiceReference.BasicResponse SaveUser(WebApplication1.ServiceReference.User user) {
            return base.Channel.SaveUser(user);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference.BasicResponse> SaveUserAsync(WebApplication1.ServiceReference.User user) {
            return base.Channel.SaveUserAsync(user);
        }
        
        public WebApplication1.ServiceReference.BasicResponse GeneratePaysheets(System.DateTime date) {
            return base.Channel.GeneratePaysheets(date);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference.BasicResponse> GeneratePaysheetsAsync(System.DateTime date) {
            return base.Channel.GeneratePaysheetsAsync(date);
        }
        
        public WebApplication1.ServiceReference.GetPaySheetsResponse GetPaySheets(System.Nullable<int> Userid) {
            return base.Channel.GetPaySheets(Userid);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference.GetPaySheetsResponse> GetPaySheetsAsync(System.Nullable<int> Userid) {
            return base.Channel.GetPaySheetsAsync(Userid);
        }
        
        public WebApplication1.ServiceReference.GetPaySheetsResponse GetPaySheetById(int id) {
            return base.Channel.GetPaySheetById(id);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference.GetPaySheetsResponse> GetPaySheetByIdAsync(int id) {
            return base.Channel.GetPaySheetByIdAsync(id);
        }
    }
}
