//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDConection.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TempBDEntities : DbContext
    {
        public TempBDEntities()
            : base("name=TempBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<st_GetUsers1_Result> st_GetUsers1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_GetUsers1_Result>("st_GetUsers1");
        }
    
        public virtual ObjectResult<st_isUserValid1_Result> st_isUserValid1(string userLogin)
        {
            var userLoginParameter = userLogin != null ?
                new ObjectParameter("UserLogin", userLogin) :
                new ObjectParameter("UserLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_isUserValid1_Result>("st_isUserValid1", userLoginParameter);
        }
    
        public virtual int St_SaveUser1(Nullable<int> userid, string name, string firstLastName, string secondLastName, Nullable<System.DateTime> insertDate, Nullable<decimal> salary, Nullable<decimal> breakFast, Nullable<decimal> savings, Nullable<bool> isActive, Nullable<int> roleid, string password, string userLogin, ObjectParameter hasError)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var firstLastNameParameter = firstLastName != null ?
                new ObjectParameter("FirstLastName", firstLastName) :
                new ObjectParameter("FirstLastName", typeof(string));
    
            var secondLastNameParameter = secondLastName != null ?
                new ObjectParameter("SecondLastName", secondLastName) :
                new ObjectParameter("SecondLastName", typeof(string));
    
            var insertDateParameter = insertDate.HasValue ?
                new ObjectParameter("InsertDate", insertDate) :
                new ObjectParameter("InsertDate", typeof(System.DateTime));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(decimal));
    
            var breakFastParameter = breakFast.HasValue ?
                new ObjectParameter("BreakFast", breakFast) :
                new ObjectParameter("BreakFast", typeof(decimal));
    
            var savingsParameter = savings.HasValue ?
                new ObjectParameter("Savings", savings) :
                new ObjectParameter("Savings", typeof(decimal));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("Roleid", roleid) :
                new ObjectParameter("Roleid", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var userLoginParameter = userLogin != null ?
                new ObjectParameter("UserLogin", userLogin) :
                new ObjectParameter("UserLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("St_SaveUser1", useridParameter, nameParameter, firstLastNameParameter, secondLastNameParameter, insertDateParameter, salaryParameter, breakFastParameter, savingsParameter, isActiveParameter, roleidParameter, passwordParameter, userLoginParameter, hasError);
        }
    
        public virtual int st_GeneratePaysheets(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_GeneratePaysheets", dateParameter);
        }
    
        public virtual ObjectResult<st_GetPaysheets_Result> st_GetPaysheets(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_GetPaysheets_Result>("st_GetPaysheets", useridParameter);
        }
    
        public virtual ObjectResult<st_GetPaysheetByid_Result> st_GetPaysheetByid(Nullable<int> paysheetid)
        {
            var paysheetidParameter = paysheetid.HasValue ?
                new ObjectParameter("Paysheetid", paysheetid) :
                new ObjectParameter("Paysheetid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_GetPaysheetByid_Result>("st_GetPaysheetByid", paysheetidParameter);
        }
    }
}
